import React, { useState, useEffect, useCallback } from 'react';

const COLUMNS = [
  { key: 'todo', label: 'To Do', evaLabel: 'Queue' },
  { key: 'in_progress', label: 'In Progress', evaLabel: 'Active' },
  { key: 'done', label: 'Done', evaLabel: 'Complete' },
];

const MOVE_TARGETS = {
  todo: ['in_progress'],
  in_progress: ['todo', 'done'],
  done: ['in_progress'],
};

const MOVE_ARROWS = {
  todo: { in_progress: '\u2192' },
  in_progress: { todo: '\u2190', done: '\u2192' },
  done: { in_progress: '\u2190' },
};

function getDeadlineClass(deadline) {
  if (!deadline) return '';
  const now = Date.now();
  const dl = new Date(deadline + (deadline.includes('T') ? '' : 'T23:59:59')).getTime();
  const hoursLeft = (dl - now) / (1000 * 60 * 60);
  if (hoursLeft < 0) return 'deadline-overdue';
  if (hoursLeft <= 24) return 'deadline-critical';
  if (hoursLeft <= 72) return 'deadline-warning';
  return 'deadline-ok';
}

function formatDeadline(deadline) {
  if (!deadline) return '';
  const now = Date.now();
  const dl = new Date(deadline + (deadline.includes('T') ? '' : 'T23:59:59')).getTime();
  const hoursLeft = (dl - now) / (1000 * 60 * 60);
  if (hoursLeft < 0) return 'OVERDUE';
  if (hoursLeft < 1) return `${Math.max(1, Math.floor(hoursLeft * 60))}m`;
  if (hoursLeft < 24) return `${Math.floor(hoursLeft)}h`;
  return `${Math.floor(hoursLeft / 24)}d`;
}

export default function KanbanBoard({ projectId, projectName, addToast, gmiMode }) {
  const [tasks, setTasks] = useState([]);
  const [newTexts, setNewTexts] = useState({ todo: '', in_progress: '', done: '' });
  const [newDeadlines, setNewDeadlines] = useState({ todo: '', in_progress: '', done: '' });
  const [aiGoal, setAiGoal] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  const loadTasks = useCallback(async () => {
    try {
      const data = await window.api.getTasksByProject(projectId);
      setTasks(data);
    } catch (err) {
      addToast('Failed to load tasks');
    }
  }, [projectId, addToast]);

  useEffect(() => {
    loadTasks();
  }, [loadTasks]);

  const handleAddTask = async (status) => {
    const text = newTexts[status].trim();
    if (!text) return;
    const deadline = newDeadlines[status] || null;
    try {
      await window.api.addTask(projectId, text, status, deadline);
      setNewTexts((prev) => ({ ...prev, [status]: '' }));
      setNewDeadlines((prev) => ({ ...prev, [status]: '' }));
      await loadTasks();
    } catch (err) {
      addToast('Failed to add task');
    }
  };

  const handleMove = async (taskId, newStatus) => {
    try {
      await window.api.updateTask(taskId, { status: newStatus });
      await loadTasks();
    } catch (err) {
      addToast('Failed to move task');
    }
  };

  const handleDelete = async (taskId) => {
    try {
      await window.api.deleteTask(taskId);
      await loadTasks();
    } catch (err) {
      addToast('Failed to delete task');
    }
  };

  const handleSetDeadline = async (taskId, deadline) => {
    try {
      await window.api.updateTask(taskId, { deadline: deadline || null });
      await loadTasks();
    } catch (err) {
      addToast('Failed to set deadline');
    }
  };

  const handleAiDelegate = async () => {
    if (!aiGoal.trim()) return;
    setAiLoading(true);
    try {
      await window.api.generateTasks(projectId, aiGoal.trim());
      setAiGoal('');
      await loadTasks();
      addToast(gmiMode ? 'Tasks generated by MAGI' : 'AI tasks added', 'success');
    } catch (err) {
      addToast(err.message || 'Failed to generate tasks');
    } finally {
      setAiLoading(false);
    }
  };

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <div className="ai-task-input">
        <label>{gmiMode ? 'MAGI Task Delegation' : 'AI Task Delegation'}</label>
        <div className="form-row">
          <input
            value={aiGoal}
            onChange={(e) => setAiGoal(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleAiDelegate()}
            placeholder={gmiMode ? 'Define objective...' : 'Describe a goal...'}
            disabled={aiLoading}
          />
          <button className="btn btn-primary btn-sm" onClick={handleAiDelegate} disabled={aiLoading}>
            {aiLoading ? <span className="spinner" /> : gmiMode ? 'Execute' : 'Generate'}
          </button>
        </div>
      </div>

      <div className="kanban">
        {COLUMNS.map((col) => {
          const colTasks = tasks.filter((t) => t.status === col.key);
          return (
            <div key={col.key} className="kanban-column">
              <div className="kanban-header">
                <span>{gmiMode ? col.evaLabel : col.label}</span>
                <span className="kanban-count">{colTasks.length}</span>
              </div>
              <div className="kanban-cards">
                {colTasks.map((task) => {
                  const dlClass = getDeadlineClass(task.deadline);
                  return (
                    <div key={task.id} className={`kanban-card ${dlClass}`}>
                      <div style={{ flex: 1 }}>
                        <div className="kanban-card-text">{task.text}</div>
                        {task.deadline && (
                          <div className={`kanban-deadline ${dlClass}`}>
                            {formatDeadline(task.deadline)}
                          </div>
                        )}
                      </div>
                      <div className="kanban-card-actions">
                        <input
                          type="date"
                          className="kanban-date-input"
                          value={task.deadline || ''}
                          onChange={(e) => handleSetDeadline(task.id, e.target.value)}
                          title="Set deadline"
                          onClick={(e) => e.stopPropagation()}
                        />
                        {(MOVE_TARGETS[col.key] || []).map((target) => (
                          <button key={target} onClick={() => handleMove(task.id, target)} title={`Move to ${target}`}>
                            {MOVE_ARROWS[col.key]?.[target] || '\u2192'}
                          </button>
                        ))}
                        <button onClick={() => handleDelete(task.id)} title="Delete" style={{ color: '#ef4444' }}>
                          &times;
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="kanban-add-row">
                <input
                  className="kanban-add-input"
                  value={newTexts[col.key]}
                  onChange={(e) => setNewTexts((prev) => ({ ...prev, [col.key]: e.target.value }))}
                  onKeyDown={(e) => e.key === 'Enter' && handleAddTask(col.key)}
                  placeholder="+ Add task..."
                />
                <input
                  type="date"
                  className="kanban-add-date"
                  value={newDeadlines[col.key]}
                  onChange={(e) => setNewDeadlines((prev) => ({ ...prev, [col.key]: e.target.value }))}
                  title="Deadline"
                />
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
